Repository SHDS-ESC/StockSimulator-BE, pull requests merged in 2025-09, with the labels that each got.

#25 Refactor: 유저 프로필 생성, 초기 세팅 기능 최종 리팩터링
  src/main/java/team/shdsesc/stocksimul/user/UserDTO.java
  src/main/java/team/shdsesc/stocksimul/user/UserEntity.java
  src/main/java/team/shdsesc/stocksimul/user/UserRepositoryCustom.java
  src/main/java/team/shdsesc/stocksimul/user/UserRepositoryCustomImpl.java
  src/main/java/team/shdsesc/stocksimul/user/UserService.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileController.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileDTO.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileEntity.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileRepositoryCustom.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileRepositoryCustomImpl.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileService.java
Labels: 개선, 버그, 추가기능

#34 턴 날짜 저장, 보유 주식 불러오기
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsController.java
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsEntity.java
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsRepository.java
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsRepositoryCustom.java
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsRepositoryCustomImpl.java
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsResponseDTO.java
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsService.java
  src/main/java/team/shdsesc/stocksimul/market/entity/Stock.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UpdateUserProfileProcessDateDTO.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileController.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileDTO.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileRepositoryCustom.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileRepositoryCustomImpl.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileService.java
Labels: 개선, 추가기능

#48 Feat: 캘린더, 턴 종료, 포트폴리오 백엔드 로직 추가
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsController.java
  src/main/java/team/shdsesc/stocksimul/holdings/HoldingsService.java
  src/main/java/team/shdsesc/stocksimul/holdings/PortfolioResponseDTO.java
  src/main/java/team/shdsesc/stocksimul/userprofile/UserProfileController.java
Labels: 개선, 추가기능

#49 실시간 뉴스 크롤링 및 스케줄링
  build.gradle
  src/main/java/team/shdsesc/stocksimul/news/NewsController.java
  src/main/java/team/shdsesc/stocksimul/news/NewsCrawlService.java
  src/main/java/team/shdsesc/stocksimul/news/NewsDTO.java
  src/main/java/team/shdsesc/stocksimul/news/NewsEntity.java
  src/main/java/team/shdsesc/stocksimul/news/NewsService.java
  src/main/java/team/shdsesc/stocksimul/news/NewsServiceImpl.java
Labels: 추가기능

#54 주문목록 조회 기능 생성
  src/main/java/team/shdsesc/stocksimul/market/repository/MarketStockRepository.java
  src/main/java/team/shdsesc/stocksimul/order/OfferController.java
  src/main/java/team/shdsesc/stocksimul/order/OfferEntity.java
  src/main/java/team/shdsesc/stocksimul/order/OfferRepository.java
  src/main/java/team/shdsesc/stocksimul/order/OfferResponseDTO.java
  src/main/java/team/shdsesc/stocksimul/order/OfferService.java
Labels: 추가기능
